version: '3'
services:
  api-php:
    container_name: api-php
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        LOCAL_USER: ${LOCAL_USER}
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      SERVICE_NAME: api-php
      SERVICE_TAGS: api
      PHP_IDE_CONFIG: "serverName=api.api.order"
    volumes:
      - .docker/php/api.ini:/usr/local/etc/php/conf.d/api.ini
      - .:/var/www/html:cached
    networks:
      - api-network
    links:
      - database:database

  database:
    image: mariadb:latest
    container_name: api-database
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql:cached
    networks:
     - api-network
#NGINX SERVICE
  api-nginx:
    image: nginx:alpine
    container_name: api-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
      - "80:80"
    volumes:
      - .docker/nginx:/etc/nginx/conf.d:ro
      - .:/var/www/html:cached
    networks:
      - api-network
    depends_on:
      - api-php
volumes:
  db-data:
#DOCKER NETWORK
networks:
  api-network:
    driver: bridge
