<?php

namespace Tests\Unit;

use App\Models\Order;
use Arr;
use Tests\TestCase;

class OrderTest extends TestCase
{
    private $order;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->order = Order::factory()->create();
    }


    /**
     * @test
     * @testdox Adding Order
     */
    public function testNewOrder()
    {
        $attr = [
            'code' => "202010098099809803945",
            'total' => 1000,
            'discount' => 900,
            'customer_id' => $this->order->customer_id
        ];

        Order::create($attr);
        self::assertDatabaseHas('orders', $attr);

    }

    /**
     * @test
     * @testdox Updating Order
     */
    public function testUpdateOrder()
    {
        $this->order->discount = null;
        $this->order->save();
        $this->assertNull($this->order->discount);
        self::assertDatabaseHas('orders', $this->order->getAttributes());
    }

    /**
     * @test
     * @testdox Showing Order
     */
    public function testShowOrder()
    {
        self::assertDatabaseHas('orders', $this->order->getAttributes());
    }

    /**
     * @test
     * @testdox Removing Order
     */
    public function testDestroyOrder()
    {
        $this->order->delete();
        self::assertSoftDeleted('orders', $this->order->getAttributes());
    }
}
